console.log(Math.PI)
console.log(Math.trunc(Math.PI))
console.log(Math.round(3.5))
console.log(Math.ceil(3.5))
console.log(Math.floor(3.5))
console.log(Math.pow(2, 3))
console.log(Math.min(6, 8, 1.4, 5))
console.log(Math.max(6, 18, 1, 5))
console.log(1 + Math.floor(Math.random() * 10))
console.log(1 + Math.floor(Math.random() * 10))
console.log(1 + Math.floor(Math.random() * 10))
console.log(1 + Math.floor(Math.random() * 10))
console.log(1 + Math.floor(Math.random() * 10))
console.log(1 + Math.floor(Math.random() * 10))